import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientComponent from "./ClientComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Codenomad",
  description: "Generated by Saurav Sharma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/lufga" rel="stylesheet" />
      </head>
      <ClientComponent interClass={`${inter.className} custom-font`}>
        {children}
      </ClientComponent>
    </html>
  );
}
